name: output-update
on:
  schedule:
    - cron:  '0 */3 * * *'
  workflow_dispatch:

jobs:
  badge-update:
    runs-on: ubuntu-latest
    container: kubevirtci/bootstrap:v20210112-b29dfd7
    steps:
    - uses: actions/checkout@v2
      with:
        token: ${{ secrets.BOT_TOKEN }}
    - name: badge update for kubevirt/hyperconverged-cluster-operator
      env:
        GITHUB_TOKEN: ${{ secrets.BOT_TOKEN }}
        SOURCE: kubevirt/hyperconverged-cluster-operator
      run: |
        echo -n $GITHUB_TOKEN > $(pwd)/token

        bazelisk run //cmd/stats -- \
          --gh-token $(pwd)/token \
          --log-level debug \
          --source ${SOURCE} \
          --path $(pwd)/output

    - name: Commit changes
      uses: EndBug/add-and-commit@v7
      with:
        author_name: Oren Cohen
        author_email: ocohen@redhat.com
        message: 'Output updated'
        add: 'output/*'
